# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{admin_assistant}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Francis Hwang"]
  s.date = %q{2010-02-24}
  s.description = %q{admin_assistant is a Rails plugin that automates a lot of features typically needed in admin interfaces.}
  s.email = %q{sera@fhwang.net}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "MIT-LICENSE",
     "README",
     "Rakefile",
     "generators/admin_assistant/admin_assistant_generator.rb",
     "generators/admin_assistant/templates/images/sort-asc.png",
     "generators/admin_assistant/templates/images/sort-desc.png",
     "generators/admin_assistant/templates/javascripts/admin_assistant.js",
     "generators/admin_assistant/templates/stylesheets/activescaffold.css",
     "generators/admin_assistant/templates/stylesheets/default.css",
     "init.rb",
     "install.rb",
     "lib/admin_assistant.rb",
     "lib/admin_assistant/active_record_column.rb",
     "lib/admin_assistant/association_target.rb",
     "lib/admin_assistant/belongs_to_column.rb",
     "lib/admin_assistant/builder.rb",
     "lib/admin_assistant/column.rb",
     "lib/admin_assistant/date_time_range_end_point_selector.rb",
     "lib/admin_assistant/default_search_column.rb",
     "lib/admin_assistant/file_column_column.rb",
     "lib/admin_assistant/form_view.rb",
     "lib/admin_assistant/helper.rb",
     "lib/admin_assistant/index.rb",
     "lib/admin_assistant/paperclip_column.rb",
     "lib/admin_assistant/polymorphic_belongs_to_column.rb",
     "lib/admin_assistant/request/autocomplete.rb",
     "lib/admin_assistant/request/base.rb",
     "lib/admin_assistant/request/create.rb",
     "lib/admin_assistant/request/destroy.rb",
     "lib/admin_assistant/request/edit.rb",
     "lib/admin_assistant/request/index.rb",
     "lib/admin_assistant/request/new.rb",
     "lib/admin_assistant/request/show.rb",
     "lib/admin_assistant/request/update.rb",
     "lib/admin_assistant/search.rb",
     "lib/admin_assistant/show_view.rb",
     "lib/admin_assistant/virtual_column.rb",
     "lib/views/_polymorphic_field_search.html.erb",
     "lib/views/_restricted_autocompleter.html.erb",
     "lib/views/autocomplete.html.erb",
     "lib/views/form.html.erb",
     "lib/views/index.html.erb",
     "lib/views/multi_form.html.erb",
     "lib/views/show.html.erb",
     "tasks/admin_assistant_tasks.rake",
     "uninstall.rb",
     "vendor/ar_query/MIT-LICENSE",
     "vendor/ar_query/README",
     "vendor/ar_query/init.rb",
     "vendor/ar_query/install.rb",
     "vendor/ar_query/lib/ar_query.rb",
     "vendor/ar_query/spec/ar_query_spec.rb",
     "vendor/ar_query/tasks/ar_query_tasks.rake",
     "vendor/ar_query/uninstall.rb"
  ]
  s.homepage = %q{http://github.com/fhwang/admin_assistant/tree/master}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{admin_assistant is a Rails plugin that automates a lot of features typically needed in admin interfaces.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<will_paginate>, [">= 0"])
    else
      s.add_dependency(%q<will_paginate>, [">= 0"])
    end
  else
    s.add_dependency(%q<will_paginate>, [">= 0"])
  end
end

