# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require(File.join(File.dirname(__FILE__), 'config', 'boot'))

require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'

require 'tasks/rails'

namespace :db do
  task :set_default_config do
    unless File.exist?('config/database.yml')
      puts "No database config found, so we'll use the default"
      FileUtils.cp('config/database.yml.example', 'config/database.yml')
    end
  end
end

task :test => :'db:set_default_config'
task :spec => :'db:set_default_config'
task :default => [:spec, :test]

